language: scala
scala:
- 2.11.3
jdk:
- oraclejdk7
script: "sbt ++2.11.3 test assembly"
env:
  global:
    secure: "SeApblifZL4B98uTaDKKsuGSaTjiS55jfbWp3HENFWQGc9GPh9J9XPeMqA7DJkkCQDXoGckjOJLT+DQEtvsyj+9B4usoY7EZUGMjMQPou91YCUTXZwiaVThuluPjTK9JzGVOfiU4OCy7vALkA4dU/1eTzLxHdDso1GbtQKv+10g="
after_success:
    "curl -k -m 90 -include -F upload=@./target/scala-2.11/skype-bot-assembly-0.1.1.jar --user $TRAVIS_USER:$TRAVIS_PASS https://skypebot.maqdev.com/upload"
