language: scala
scala:
- 2.11.3
jdk:
- oraclejdk7
script: sbt ++2.11.3 test assembly
env:
  global:
  - secure: AQqQzAN8MNNGjOjDD8goKAtAA4XNq6CcQnuQbWS+QoGd5EFY5U7dkyBSHAEcckaaIjA0qQj0BXnFnM/6W9cJ6I+ceSo+caoOmWFdoOtolX9UH/7emVuvCJYOK6rZCKjurUFAKWi1cbP2u4yeuaQnIPAwRVEXTNED1udUlgUkF84=
  - secure: X0M8zrK6q4SA66eke1oaSjQRlxOuWaXkCadL+4zhrFIHmt3YHZlUnrdHpb2U8fUyTX6rAZolQ+2dsxjF7/3RqCUfsztlnPKxlNZKqH4CRhQ3/sZPNDWzAErUVFj1qdQFMKhIup7zBOukWxFCN02dZwXRIvXaNoOlVU4NYsIs+Ms=
after_success: curl -k -m 90 -include -F upload=@./target/scala-2.11/skype-bot-assembly-0.1.1.jar
  --user $UP_USER:$UP_PWD https://bot.maqdev.com/upload
